# -*- coding: utf-8 -*-
"""A03 - PYTHON.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XMMnynlnu6lTDNzMHWUhjsfTBtVZTz_k

Alan Almaraz   -         24 de Agosto de 2024
"""

import pandas as nd
datos = nd.read_excel("datosCT.xlsx")

datos["Utilidad"] = datos["Ingreso"] - datos["Gasto"]
datos

N = 0
P = 0
for i in datos["Utilidad"]:
      if i < 0:
        N = N + 1
        P = P + datos.loc[datos["Utilidad"] == i, "Gasto"]

print("El promedio de Gastos en los meses que la Utilidad fue negativa es " + str(P/N))

print("Los ingresos totales del año es de " + str(datos["Ingreso"].sum()))

import numpy as np

A = np.array([
    [1,2],
    [3,4]
])
B = np.array([
    [2],
    [4]
])

A @ B